### ISSUE TITLE
Hedensted kommune

### ISSUE THREAD

**Issue by PGLDK** [briis/renoweb#12]
Hedensted kommune benytter renoweb, ( https://hedensted.renoweb.dk/Legacy/selvbetjening/mit_affald.aspx )
men returnerer følgende:

Ved du hvorfor?

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 164, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/renoweb/config_flow.py", line 58, in async_step_user
    unique_data = await renoweb.find_renoweb_ids(
  File "/usr/local/lib/python3.9/site-packages/pyrenoweb/client.py", line 175, in find_renoweb_ids
    json_data = await self.get_roadids(municipality_id, zipcode, street_name)
  File "/usr/local/lib/python3.9/site-packages/pyrenoweb/client.py", line 121, in get_roadids
    for row in json_data["list"]:
KeyError: 'list'

**Comment by PGLDK** [comment]
Det lader til hedensted har kode 766 - den giver samme fejl.

**Comment by briis** [comment]
Jeg kan godt se at Hedensted bruger renoweb, men deres kommune id optræder ikke i det API jeg kigger i, og derfor finder den ikke adressen. Jeg har brugt lidt på at gå deres website igennem for at se om de bruger et andet ID til deres opslag, men kan ikke finde noget. Så lige nu er jeg blank i forhold til hvorfor denne kommune ikke virker.

**Comment by PGLDK** [comment]
Tak for forsøget Bjarne - Det virker mystisk da Horsens virker fint og er helt identisk med Hedensted på Renoweb o.l. Hvad er dit indtryk, Tror du Renoweb er behjælpelige med at opklare det, eller skal jeg bruge min tid på noget andet? :-)

**Comment by briis** [comment]
Jeg er ikke sikker på Renoweb vil være behjælpsom. De API koder der bruges er noget der er blevet 'sniffet' af en anden bruger end mig og vi riskerer de lukker for dem.
Jeg tror umiddelbart det er en anden kommune kode end de 766, der skal bruges. Jeg har lavet et lille program hvor jeg klan teste hver eneste kommune id sammen med et post nummer og en adresse, og det kan jeg godt prøve, men så skal du lige sende mig en adresse jeg kan teste på. Du kan evt. sende den til min private email, så den ikke står her på det åbne internet.

**Comment by briis** [comment]
Min mailadresse er bjarne@briis.com

**Comment by PGLDK** [comment]
Tak - har sendt dig en mail.

**Comment by briis** [comment]
Jeg har nu tæsket 800 ID'er igennem, med det post nr og vejnavn du sendte mig, men intet kommer tilbage. Jeg ved helt ærlig ikke hvorfor, men jeg kan desværre ikke gøre mere lige nu.

**Comment by pless84** [comment]
Ka det passe Hedensted stadig ikke virker?

**Comment by briis** [comment]
Desværre ja. Jeg tror der flere måder at tilgå Renoweb data, og det API jeg benytter understøtter kun de kommuner der er på README filen. Beklager.

**Comment by PGLDK** [comment]
Fik den aldrig til at virke nej, men denne virker på hedensted kommune (https://api.harders-it.dk/garbage)

**Comment by pless84** [comment]
> Fik den aldrig til at virke nej, men denne virker på hedensted kommune (https://api.harders-it.dk/garbage)

Tak :)

**Comment by briis** [comment]
Selv tak. Jeg kigger lige i det link du har sendt for at se om det også kunne integreres - ingen løfter dog 😀
