### ISSUE TITLE
Error setting up integration

### ISSUE THREAD

**Issue by MathStand** [briis/renoweb#13]
Hi, after installing with HACS and adding the integration with address, zip, etc., i get the following error:

> This error originated from a custom integration.
> 
> Logger: homeassistant.config_entries
> Source: custom_components/renoweb/__init__.py:84
> Integration: RenoWeb Garbage Collection (documentation, issues)
> First occurred: 11:13:24 AM (3 occurrences)
> Last logged: 11:17:53 AM
> 
> Error setting up entry None for renoweb
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/renoweb/__init__.py", line 84, in async_setup_entry
>     await renoweb.get_pickup_data()
>   File "/usr/local/lib/python3.9/site-packages/pyrenoweb/client.py", line 258, in get_pickup_data
>     for row in json_data["list"]:
> KeyError: 'list'

Any idea what could be wrong?

Best regards
Mathias

**Comment by MathStand** [comment]
I just tried with the neighbour address and worked perfectly.
My address is "3B". Entering the address without the "B" works as well.
